package golden.dao;

import java.util.ArrayList;
import java.util.List;

import com.alibaba.fastjson.JSONObject;

import golden.model.Article;
import golden.model.Calendar;
import golden.model.Collection;
import golden.model.Course;
import golden.model.HasReadWordsWithBLOBs;
import golden.model.Homework;
import golden.model.Message;
import golden.model.Resource;
import golden.model.Student;
import golden.model.StudentCourse;
import golden.model.StudentHomework;
import golden.model.Teacher;
import golden.model.Video;
import golden.model.WordListWithBLOBs;
import golden.tempmodel.Art_page;
import golden.tempmodel.ChatList;
import golden.tempmodel.SearchCourse;
import golden.tempmodel.Tea_image;
import golden.tempmodel.Vid_page;
import golden.tempmodel.article_1;
import golden.tempmodel.collection_1;

public interface userdao {
	public WordListWithBLOBs selectbyword_id(Integer word_id);
    public HasReadWordsWithBLOBs selectby_studentid(Integer student_id);
    public Calendar select_calendar_by_studentid(Integer student_id);
	public List<Object> selectbyword(String word);
	public int collection(Collection collec);
	public collection_1 select_collection(Integer student_id);
	public List<article_1> get_text();
	public int update_text(article_1 arti);
	public Teacher sel_tea_by_tea_number(String tea_number);
	public int add_tea(Teacher tea);
	public Student sel_stu_by_stu_number(String stu_num);
	public int upd_tea(Teacher tea);
	public int upd_pwd(Teacher tea);
	public int upd_ima(Tea_image tea_image);
	public List<Course> get_cou(Integer tea_id);
	public Course get_cou_by_couNum(String cou_num);
	public int upd_cou_by_id(Course cou);
	public String get_last_cou_rec();
	public int cre_new_cou(Course cou);
	public List<String> get_cou_by_teaId(Integer tea_id);
	public List<String> get_stuNum_by_couNum(String cou_num);
	public List<Message> get_mes_by_teaId(Integer tea_id);
	public int upd_mes(Message mes);
	public int del_stu(Integer stu_id);
	public List<Homework> get_hom_by_couId(Integer cou_id);
	public StudentHomework get_stu_hom(StudentHomework temp);
	public List<Student> get_all_stu();
	public int del_stu_cou(StudentCourse stu_cou);
	public List<Resource> get_res();
	public int cre_res(Resource res);
	public Vid_page get_vid(Integer offset, Integer size);
	public int cre_vid(Video vid);
	public Art_page get_art(Integer offset, Integer size);
	public int cre_art(Article art);
	public Article get_art_by_id(Integer art_id);
	public List<Course> get_cou_list_by_stuNum(String stu_num);
	public Course get_cou_by_couId(Integer cou_id);
	public Teacher get_tea_dea(Integer tea_id);
	public Homework get_hom_by_homId(Integer hom_id);
	public int upl_ans(StudentHomework stu_hom);
	public SearchCourse get_cou_Teaname_by_couNum(String cou_num);
	public int join_cou(StudentCourse stu_cou);
	public List<ChatList> get_chat_list(String stu_num);
	public List<Message> get_mes(Message mes);
	public int send_mes(Message mes);
}
